# Configuration file for the Sphinx documentation builder.
# Generated by Lative. See https://www.sphinx-doc.org/en/master/usage/configuration.html

project = 'Thunderstorm Origami Analyzer'
author = 'Aun Al Atiat'
copyright = '2026, AlAtiat'

# EPUB3.
version = '0.0.4'
release = '0.0.4'

extensions = [
    'sphinx.ext.mathjax',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

# EPUB metadata.
epub_title = 'Thunderstorm Origami Analyzer'
epub_author = 'Aun Al Atiat'
epub_publisher = 'Aun Al Atiat'
epub_copyright = copyright

# Render numbered figures/tables (matches the LaTeX source).
numfig = True

# Define pandoc's `raw-latex` role so any inline LaTeX it could not convert is ignored
rst_prolog = """
.. role:: raw-latex(raw)
   :format: latex
"""
